.github/workflows/test_integration.yaml, pkg/kind/cluster.go, pkg/kind/kind.go, pkg/kind/kong_proxy_cluster_configuration.go
Adding the *rest.Config as a returnable to the kind.Cluster
interface adds convenience for callers who want to generate
custom clientsets for their own typed clients for the cluster.
=> feat: add *rest.Config to kind.Cluster

pkg/kind/kong_proxy.go, pkg/kind/kong_proxy_cluster_configuration.go, test/integration/kind_cluster_test.go
- fix: correct a timing issue that would cause a closed chan panic
- fix: no report needed if the context is "done"
=> Proxy readiness channel cleanup

pkg/kind/cluster.go, pkg/kind/kong_cluster.go
This PR adds a shim for allowing overrides of cluster names on `Deploy()` from a proxy only configuration.
=> feat: allow custom name cluster deploys

pkg/kind/kong_proxy_readiness.go, pkg/kind/vars.go
Adds fields for the HTTPS proxy URL and proxy IP to readiness events.
Needed for tests related to https://github.com/Kong/kubernetes-ingress-controller/issues/1354
=> Add HTTPS URL and proxy IP

docs/install.sh
Use bash for the install script instead of sh. The KTF install script
relies on some bash-specific shell builtins (set -o pipefail) and won't
run with plain sh.
This partially addresses the issue encountered in https://github.com/Kong/charts/runs/3060680578?check_suite_focus=true
=> fix: use bash for install script

internal/cmd/environments.go, pkg/clusters/addons/kong/builder.go, pkg/clusters/addons/kong/kong.go, test/integration/kind_cluster_test.go
This PR adds tooling to enable the latent capability to deploy a test environment with the Kong addon configured in a "proxy only" mode in both Go library and CLI use cases.
This is a backwards incompatible change, because the default used to be "proxy only" and now the default is to enable the controller.
- feat: enable proxy-only mode for kong addon
- feat: enable --kong-disable-controller flag for env cli
- feat: add --kong-dbmode flag for env CLI
- feat: environments cli aliases
- chore: add tests to validate default kong addon configurations
- chore: add test for proxy only deployment
=> [feat] proxy only mode

.github/workflows/tests.yaml, .gitignore, internal/cmd/environments.go, pkg/environments/builder.go
Clusters already have the ability to designate a specific
Kubernetes version, this patch forwards that ability up
through the environment which creates the cluster and makes
the functionality available via CLI using the newly added
flag ktf env create --kubernetes-version <VERSION>.
In support of https://github.com/Kong/charts/issues/391
=> [feat] add k8s version for environment builder

pkg/clusters/types/gke/builder.go, pkg/clusters/types/gke/cluster.go, pkg/clusters/types/gke/utils.go, pkg/clusters/types/gke/vars.go, test/e2e/gke_cluster_test.go
- chore: move gke var names into gke pkg
- chore: refactor gke auth into discreet fn
- feat: enable gke clusters from existing
Unblocks work going on in https://github.com/Kong/kubernetes-ingress-controller/issues/1095
=> [feat] enable gke clusters from existing

pkg/clusters/utils.go, pkg/utils/kubernetes/generators/ingress.go, test/e2e/gke_cluster_test.go
- feat: add a generator which determines ing version
- feat: add utils to handle ing version auto on old clusters
Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1614
=> [feat] legacy ingress utils

pkg/clusters/cluster.go, pkg/clusters/types/gke/cluster.go, pkg/clusters/types/kind/cluster.go, test/e2e/gke_cluster_test.go, test/integration/kind_version_test.go
Adds a convenience method to get the cluster version, and requires that all cluster implementations implement one.
Also fixes an issue in the release tests with version comparisons.
=> feat: add version check to cluster interface

pkg/clusters/types/gke/builder.go, pkg/clusters/types/gke/utils.go, pkg/clusters/types/gke/vars.go, test/e2e/gke_cluster_test.go
This patch adds a label which makes it easy to identify when a GKE cluster was created by KTF, and for convenience the `client_id` of the IAM service account which performed the original creation.
This also removes a version check when creating the k8s client, as new use cases emerge that want to build the client async to the cluster creation and so the version check isn't appropriate.
Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1627
Required By https://github.com/Kong/kubernetes-ingress-controller/pull/1631
=> feat: ktf labels gke clusters

Makefile, internal/utils/kubeconfig.go, pkg/clusters/addons/knative/knative.go, pkg/clusters/addons/kong/kong.go, test/integration/knative_test.go
This PR adds an addon to deploy [Knative](https://knative.dev) on test clusters.
Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1637
Blocker For https://github.com/Kong/kubernetes-ingress-controller/pull/1646
=> feat: knative addon for clusters

pkg/utils/kubernetes/generators/labels.go, pkg/utils/kubernetes/generators/transient.go, test/integration/generators_test.go
This patch adds some tooling which will help provide more isolation and automated cleanup of testing resources for test suites implementing KTF clusters.
Resolves https://github.com/Kong/kubernetes-testing-framework/issues/17
=> feat: add utils for generating test namespaces

pkg/clusters/addons/kong/kong.go
At times the repo add command might throw an error
even if ultimately the repo is already there.
This patch adds the `--force-overwrite` options when
adding the kong repo to update it to the latest value
regardless of whether or not it already existed.
Resolves https://github.com/Kong/kubernetes-testing-framework/issues/80
=> fix: kong addon deployment idemopotence

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/enhancement.yaml
This PR adds the same issue template we use already in the [KIC](https://github.com/kong/kubernetes-ingress-controller) for consistency.
=> docs: add issue templates

pkg/clusters/addons/knative/knative.go
0.18.0 is the earliest version that uses v1 CRDs. No apparent issues with KIC tests, which run fine with the new version.
=> Bump Knative to 0.18.0

.github/workflows/tests.yaml, Makefile, pkg/clusters/addons/kong/addon.go, test/integration/enterprise_test.go, test/integration/generators_test.go, test/integration/istio_test.go, test/integration/kind_cluster_test.go, test/integration/kind_version_test.go, test/integration/knative_test.go, test/integration/metallb_test.go, test/integration/postgres_test.go
Re-enables parallel integration tests: This was disabled previously because of problems found with Github Actions when spawning multiple clusters, but this patch includes a specific limit of 2 for that environment to try and reduce that problem but still squeeze out some extra time out of the tests there.
Additionally in this PR I fixed an issue with the Kong addon which I found to be causing test flakes for the enterprise integration tests: we were configuring the number of alphabetic characters required for a generated secret in place of the numbers of symbols required. This has been fixed and the result is passwords which are still long, but don't include some characters which require special escaping or handling (which would appear to be totally fine in the use case of testing). This …
=> fix: re-enable integration tests parallelization

internal/cmd/ktf/environments.go, internal/utils/namespaces.go, pkg/clusters/addons/httpbin/addon.go, pkg/clusters/addons/httpbin/builder.go, pkg/clusters/addons/istio/addon.go, pkg/clusters/addons/knative/knative.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/metallb/metallb.go, pkg/environments/implementation.go, pkg/utils/kubernetes/generators/ingress.go, pkg/utils/networking/http.go, test/e2e/gke_cluster_test.go, test/integration/enterprise_test.go, test/integration/generators_test.go, test/integration/istio_test.go, test/integration/kind_cluster_test.go, test/integration/suite_test.go
This PR adds a new `httpbin` addon as that was becoming a common workflow across all testing, as well as making some other general improvements:
- feat: add new generator for ingress from container spec
- feat: add httpbin cluster addon
- chore: add httpbin addon into integration tests
- feat: enable istio addon in ktf cli
- feat: enable httpbion addon in ktf cli
- chore: use availability instead of readiness
- feat: http wait function in networking utils
Resolves https://github.com/Kong/kubernetes-testing-framework/issues/126
=> feat: httpbin addon

.github/workflows/release-testing.yaml, .github/workflows/tests.yaml, pkg/clusters/addons/kong/enterprise.go, pkg/clusters/addons/kong/enterprise_test.go, test/integration/enterprise_test.go, test/integration/suite_test.go
This patch adds some utilities for retrieving and validating the Kong Enterprise License from the environment, and plugs them into the existing test suite.
This is in support of providing a consistent means between KTF and KIC for which environment variable contains the license data, and otherwise to just provide a consistent way to get it.
The validation added also allows tests to fail faster if the license data is somehow invalid, or if an otherwise valid license is out of date.
=> feat: add enterprise kong license utils

.github/workflows/lint.yaml, internal/cmd/ktf/environments.go, pkg/clusters/addons/certmanager/addon.go, pkg/clusters/addons/istio/addon.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/utils.go, pkg/utils/github/release.go, test/integration/certmanager_test.go, test/integration/istio_test.go
This patch adds a [CertManager](https://cert-manager.io) addon as well as a few new utility functions that help support it.
This is helpful for KIC when we would want to test TLS, and also helpful for https://github.com/Kong/kubernetes-testing-framework/issues/147 in case we want to use [Harbor](https://github.com/goharbor) (it requires `cert-manager`).
=> feat: cert-manager addon

pkg/clusters/addons/loadimage/addon.go, pkg/clusters/addons/loadimage/builder.go, pkg/clusters/addons/loadimage/cluster_implementations.go
This is one of two proposals to add image loading to KTF, broken out of #149. It is mutually exclusive with https://github.com/Kong/kubernetes-testing-framework/pull/152. Only one of the two should be merged.
This approach provides a plugin for loading images following the standard KTF plugin pattern. Building a cluster that includes this plugin will attempt to load an image and report a failure if that is not possible or if that is unsuccessful.
This addition lacks tests because KIND will not (contrary to my earlier expectations) load an image not already present on the host machine. We'd need to run `docker pull` or similar to ensure the requested image is available locally, and I'm loathe to screw around with that. My original test code is available at …
=> feat: add load image addon

CHANGELOG.md, pkg/clusters/addons/certmanager/addon.go
Resolves https://github.com/Kong/kubernetes-testing-framework/issues/159
=> fix: timing issue with cert-manager webhook

internal/utils/namespaces.go, pkg/clusters/addons.go, pkg/clusters/addons/certmanager/addon.go, pkg/clusters/addons/httpbin/addon.go, pkg/clusters/addons/istio/addon.go, pkg/clusters/addons/knative/knative.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/loadimage/addon.go, pkg/clusters/addons/metallb/metallb.go, pkg/clusters/types/gke/builder.go, pkg/clusters/types/gke/cluster.go, pkg/clusters/types/kind/builder.go, pkg/clusters/types/kind/cluster.go, pkg/clusters/types/kind/utils.go, pkg/clusters/utils.go, pkg/environments/builder.go
This patch includes several quality of life improvements for addons, some of which just improve how things currently work and some which are features in preparation for upcoming addons (e.g. https://github.com/Kong/kubernetes-testing-framework/issues/147):
- improvements to the consistency of the generic namespace readiness checking utility functions
- the ability for addons to express their dependencies on other addons
=> chore: qol improvements for cluster addons

pkg/clusters/addons/kong/addon.go
We're going to need to test some TLS route stuff, thus...
=> Add a TLS TCP port 8899 to Kong addon

pkg/clusters/addons/knative/knative.go
It's technically possible at times for the available
replica count to be higher than the replicas desired
in the spec, but this should not stop addon readiness.
This resolves #172
=> fix: allow extra replicas for availability

CHANGELOG.md, pkg/clusters/addons/kong/addon.go
Needed to fix https://github.com/Kong/kubernetes-ingress-controller/issues/2126
Tests that delete and restore their upstreams in non-default workspaces may be affected by the upstream event fix in https://docs.konghq.com/gateway/changelog/#core-6
=> Bump Enterprise to 2.7 and release 0.11.1

pkg/clusters/addons/knative/builder.go, pkg/clusters/addons/knative/knative.go, pkg/utils/github/release.go
Support user-supplied Knative versions, and default to the latest release at this time.
Basic PoC using the controller integration tests:
[knative_test.txt](https://github.com/Kong/kubernetes-testing-framework/files/7899557/knative_test.txt)
```
10:08:55-0800 esenin $ kubectl describe po -n knative-serving | grep release=
serving.knative.dev/release=v1.1.1
```
=> feat(knative) support user-supplied versions

.github/workflows/lint.yaml, pkg/clusters/addons/knative/knative.go
Fix #208 using something sort of like `require.Eventually()`
Fix is speculative based on the observed issue. We have no guaranteed means of reproducing the issue to confirm.
=> fix(knative) add retry to core deployment

internal/cmd/ktf/environments.go
This is just something I do manually with a fair amount of frequency so I figured I would add it to the CLI.
In time we do need to change how the CLI is structured so that flags belong to the addon component instead of being general to environment creation, but for the moment this is just a quick add that provides a lot of value for running tests.
=> feat: add flag to enable LB SVC for kong admin in CLI

pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/vars.go
Exposes the default TCP routing port for the Kong Addon as a far, similar to what already exists for UDP. Also adds references to the var instead of literals where applicable.
Needed for https://github.com/Kong/kubernetes-ingress-controller/issues/2086
=> feat: expose default TCP port for Kong addon

internal/utils/cluster_init.go
Back when we first made KTF we added a check to wait for the service account that would be used for testing until it's `Secret` was generated. Modern versions of Kubernetes since `v1.24.0` have a different implementation for `ServiceAccounts` which doesn't make this secret available like it used to be. As such this patch removes the check as it is irrelevant going forward and is breaking recent deployments.
=> fix: remove cluster init token check

internal/cmd/ktf/environments.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go, test/integration/kongaddon_test.go
This PR adds kong-ingress-controller-image that sets the ingress controller image used for deployment.
=> feat: add kong-ingress-controller-image flag

pkg/clusters/addons/kuma/addon.go, pkg/clusters/addons/kuma/builder.go
Add a Kuma addon. Following the recent ServiceAccount token integration breakage, we need to add Kuma to integration tests. First go is a bare-bones addon that can deploy an MTLS mesh policy and not much else.
We'll probably be a quite limited if we want to do anything with this beyond basic smoke testing: Kuma apparently lacks a clientset, so we either need to contribute that or build everything from YAML. That works in Helm tests but is iffy in the Golang tests.
Example usage in this KIC draft: https://github.com/Kong/kubernetes-ingress-controller/pull/2635
=> feat: add Kuma addon

pkg/clusters/types/gke/builder.go
Disable the GKE native Ingress controller. This controller interacts with classless Ingresses, which can interfere with our tests.
We encountered an apparent race condition where https://github.com/Kong/kubernetes-ingress-controller/blob/main/test/integration/ingress_test.go#L330 failed because the resource had been updated after we got it, blocking our update. It's not actually clear if the classless interactions are the cause here--they shouldn't be because the failure was the update to make the resource classless. However, the only unexpected configuration I can see on the Ingress is related to the GKE controller, so absent other explanations, figured it was worth a shot.
Test KIC run in https://github.com/Kong/kubernetes-ingress-controller/pull/2634. Note that while the additional …
=> feat(gke) disable Google Ingress controller

CHANGELOG.md, go.mod, go.sum, test/integration/knative_test.go
Adds changes since 0.14.2 to the changelog under 0.15.0.
Cherry-picks https://github.com/Kong/kubernetes-testing-framework/pull/305 since that doesn't appear to be re-creating properly and is still using an old license in tests.
Refactored a flaky test to fix #308
=> Add changelog for 0.15.0

test/e2e/gke_cluster_test.go
https://github.com/Kong/kubernetes-testing-framework/runs/7345390116?check_suite_focus=true failed because GKE 1.19 is no longer available. Bumped to latest version on the regular channel.
=> chore: bump GKE test version

.github/workflows/release-testing.yaml, .github/workflows/tests.yaml
At the same time I've added `PULP_PASSWORD` secret to Dependabot's secrets and to `integration-tests` environment secrets.
=> chore(ci): use kong-license action to obtain license from pulp

pkg/clusters/addons.go, pkg/clusters/addons/certmanager/addon.go, pkg/clusters/addons/httpbin/addon.go, pkg/clusters/addons/istio/addon.go, pkg/clusters/addons/knative/knative.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go, pkg/clusters/addons/kuma/addon.go, pkg/clusters/addons/loadimage/addon.go, pkg/clusters/addons/metallb/metallb.go, pkg/clusters/addons/registry/addon.go, pkg/clusters/cleanup.go
Related to #306. Not sure what @randmonkey had in progress also but I figure there's room for both.
Adds log level support to the Kong Addon, which isn't directly related to this, but I noticed that the dumped Kong logs were at the default info level and thought we'd probably want it also.
Adds `DumpDiagnostics()` functions to Cleaner and Addon types. The Cleaner function takes a context and string and:
- Dumps all resources via kubectl.
- Describes all resources via kubectl.
- Gathers logs from all Pods.
- Runs all enabled Addon `DumpDiagnostics()` functions.
- Writes the outputs to various files in a tmpdir and the input string to meta.txt. meta.txt will usually be the test name, to provide an alternative to logging the directory in the caller and trawling job output to match the dump …
=> Add diagnostic dump framework

CHANGELOG.md, go.mod, go.sum, internal/cmd/ktf/environments.go, pkg/clusters/addons/certmanager/addon.go, pkg/clusters/addons/kuma/addon.go, pkg/clusters/types/kind/builder.go, pkg/clusters/types/kind/utils.go, pkg/clusters/utils.go, pkg/environments/builder.go, test/integration/calico_test.go, test/integration/certmanager_test.go, test/integration/clusterutils_test.go
The purpose of this task is to add [Calico](https://projectcalico.docs.tigera.io) as an alternative CNI option for `kind` clusters as this will enable the validation and testing of `NetworkPolicy` resources.
=> feat: add calico CNI option for kind clusters

pkg/clusters/addons/kuma/addon.go
increase retry times to wait more time (1m) for Kuma webhook startup. Try to solve [KIC#2733](https://github.com/Kong/kubernetes-ingress-controller/issues/2733).
=> fix: increase retry timeout to 1m on creating mesh in kuma

CHANGELOG.md, pkg/clusters/addons/kuma/addon.go
- refactor `enableMTLS` in kuma addon to use `select` for retrying
- update CHANGELOG.md for releasing v0.19.0 of KTF
=> chore: refactor enableMTLS in kuma addon and update CHANGELOG.md

CHANGELOG.md, pkg/clusters/cleanup.go
Didn't change the command after copy pasting originally, whoops.
=> fix: use correct command for describe

CHANGELOG.md, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go, pkg/clusters/addons/kong/vars.go, pkg/utils/docker/kind.go, test/integration/kongaddon_test.go
This was originally made in support of https://github.com/Kong/kubernetes-ingress-controller/issues/2808 but became detached from it because a different testing route was taken. It's still valuable to be able to select the service type however, so I figured might as well add it anyway.
=> feat: allow service type selection for kong proxy

CHANGELOG.md, go.mod, go.sum, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go, test/integration/enterprise_test.go, test/integration/istio_test.go, test/integration/kind_cluster_test.go, test/integration/kongaddon_test.go, test/integration/metallb_test.go, test/integration/postgres_test.go, test/integration/registry_test.go
Add a new WithProxyEnvVar function to the Kong addon builder. This takes a name and value and adds an environment variable with that name and value to the Kong container.
Update changelog in preparation for a 0.20 release.
Temporarily pin the Kubernetes version to mitigate #364
=> Support arbitrary Kong proxy envvars and release 0.20

go.mod, go.sum, pkg/clusters/addons/metallb/metallb.go, test/integration/enterprise_test.go, test/integration/istio_test.go, test/integration/kongaddon_test.go, test/integration/metallb_test.go, test/integration/postgres_test.go, test/integration/registry_test.go
This PR bumps the metallb manifest to use [v0.13.5](https://github.com/metallb/metallb/releases/tag/v0.13.5) which drops usage of pod security policy (which is unavailable in k8s v1.25+).
Initially I wanted to avoid using the [`IPAddressPool`](https://metallb.universe.tf/configuration/#defining-the-ips-to-assign-to-the-load-balancer-services) but on the kind cluster that I performed the testing the services would never get the IPs.
Fixes #364
Probably we should use a different mechanism of deployment, not using `kubectl` (like mentioned  in the comment in metallb addon's source code).
=> chore: bump metallb to v0.13.5 to support k8s v1.25

CHANGELOG.md, pkg/clusters/addons/metallb/metallb.go
delete `IPAddressPool` and `L2Advertisement` resource if the resource exists before creating in `metallb` addon. Fixes #381.
=> fix: delete resources if existed in metallb addon

CHANGELOG.md, pkg/clusters/addons/metallb/metallb.go
metallb IPAddressPool creation failures are currently logging lines like:
```
failed to deploy addon metallb: failed to create metallb.io/v1beta1 IPAddressPool: context deadline exceeded, last error on create: Post "https://127.0.0.1:36091/apis/metallb.io/v1beta1/namespaces/metallb-system/ipaddresspools": context deadline exceeded
```
Code review suggests that since we're assigning lastErr after the creation attempt but before the switch handling the `ctx.Done()` case, where the switch context is the same context we pass to the create request, the last create request fails because the context is done and then wipes out the previous error. That previous error was hopefully more interesting, because it should be whatever prevented the loop from completing before the context expired.
Moving …
=> fix: move error log and release 0.22.1

CHANGELOG.md, pkg/clusters/addons/metallb/metallb.go
Increase this. E2E failed almost always once per instance with the old timeout. It failed in one out of ~ten with 2 minutes. May as well let it run.
Alternative is that we just disable the webhook, we don't really need it.
If you merge, please initiate the release job. Auto-merge is off, I'll do it it's still around by morning.
=> chore: increase the metallb timeout and release 0.22.2

CHANGELOG.md, pkg/clusters/addons/metallb/metallb.go, pkg/clusters/addons/metallb/metallb_test.go
For some test environments, 10 IP addresses might not be enough resulting in situations where the IPs for some services are perpetually pending, causing tests to time out and fail.
This PR should help to some extent by extending the range from 10 to 150 IPs.
This also adds a release note for v0.22.3 to release it after this gets merged.
=> fix: use wider IP range for metallb ipaddresspool

pkg/clusters/addons/metallb/metallb.go, pkg/clusters/utils.go, pkg/utils/kubernetes/kubectl/kustomize.go
Set the metallb admission controller to ignore. Our IPAddressPools and L2Advertisements are static and work. The admission controller has a habit of not coming online and blocking the deploy. Ignoring its failures avoids this.
Add a kustomize utility and refactor the metallb deploy to use it.
The kustomize utility is generic enough to go into KTF. The specific patches and Kustomization structs will be provided by individual tests (or, in KTF's case, plugins). This is adapted from the code originally introduced in https://github.com/Kong/kubernetes-ingress-controller/pull/2995 and would replace it in KIC once released. It differs in that it instead takes a variadic manifest argument and appends these to the resources, rather than replacing the resources entirely with a single manifest …
=> fix: ignore metallb admission

pkg/clusters/cluster.go, pkg/clusters/types/kind/builder.go, pkg/clusters/types/kind/cluster.go, pkg/environments/builder.go
Add environment functionality to build an environment given a cluster builder, in addition to the current options of a pre-built cluster or an opinionated default KIND cluster builder.
The environment design doesn't seem to offer a good means of configuring functionality not supported across all cluster types. The image load addon is a prime example, where the current implementation is closely tied to KIND functionality and there is no GKE implementation (though there could be). As the cluster builders are all type-specific, they provide the most obvious injection point for type-specific functionality.
Injecting these into an environment prior to the environment build does not require significant changes to the environment builder, since it already needed to build the cluster when using …
=> Add environment support for provided cluster builders

.github/workflows/release-testing.yaml
Attempt to address https://github.com/Kong/kubernetes-testing-framework/issues/337
[The github documentation ](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) states that the `GITHUB_TOKEN` should not be used for triggering a new workflow run from github actions itself. Using `GITHUB_TOKEN` prevents other workflows from triggering to avoid recursive workflow runs. It stopped working for us some time ago. This is an attempt to make it working again by changing the token used during the checkout to PAT.
=> chore(ci): use PAT for tagging instead of GITHUB_TOKEN

.github/workflows/tests.yaml, Makefile, test/integration/calico_test.go
This PR makes it so that ktf integration tests are using a matrix on CI now in such a way that each test runs in it's own workflow. This way we don't expect one test disrupting another one or problems with performance (since default, hosted Github runners are generally known of their not so great performance).
Additionally, this PR adds `integration-tests-passed` job, which has been made required from now on. This makes this setup "scalable" in a way such that when new integration tests are added no actions have to be done in order to make the CI happy.
This also shuffles around the environments to prevent spam in Github conversation view: where not needed the `environment: "integration-tests"` setting has been removed and an additional `setup-kong-license` job has been added to pull the …
=> tests: use Github Actions matrix for integration tests

pkg/clusters/addons/metallb/metallb.go
Bump to https://metallb.universe.tf/release-notes/#version-0-13-7
=> chore: bump metallb to v0.13.7

go.mod, go.sum, pkg/clusters/addons/kong/addon.go
This PR bump deck to 1.15.1 and fixes an issue with `file.KongStateToFile` requiring the kong version as an argument.
The deck change was introduced by https://github.com/Kong/deck/commit/f5c7c56c0633fae605c517d3af4472109471ff27
Bumps [github.com/kong/deck](https://github.com/kong/deck) from 1.14.0 to 1.15.1.
- [Release notes](https://github.com/kong/deck/releases)
- [Changelog](https://github.com/Kong/deck/blob/main/CHANGELOG.md)
- [Commits](https://github.com/kong/deck/compare/v1.14.0...v1.15.1)
---
updated-dependencies:
- dependency-name: github.com/kong/deck dependency-type: direct:production update-type: version-update:semver-minor ...
=> fix(deck): fix deck 1.15.1 requiring the kong version in call of `file.KongStateToFile`

.github/workflows/lint.yaml, .golangci.yaml, Makefile, internal/utils/cluster_init.go, pkg/clusters/addons/httpbin/addon.go, pkg/clusters/types/kind/cluster.go, pkg/clusters/utils.go, pkg/utils/kong/fake_admin_api_test.go
This PR:
- unpins golangci-lint version from [lint workflow](https://github.com/Kong/kubernetes-testing-framework/blob/3dabf4568c7b58b49807035a11f042c52299aeb9/.github/workflows/lint.yaml#L28-L29)
- removes deprecated linters from `golangci-lint.yaml` config
- adds config for `gci`
- fixes linter errors
=> chore: update linter settings

.gitignore
Adds a few rules to gitignore, that will make the life easier by ignoring ide and mac os related files.
=> chore: update .gitignore with common files that should not be commited

pkg/clusters/addons/kong/addon.go
Use `postgresql.auth.username` and `postgresql.auth.database` instead of  `postgresql.postgresqlUsername` and `postgresql.postgresqlDatabase` as the later ones were removed from kong chart by https://github.com/Kong/charts/commit/2e89647d86ec7c8fa2a2a1697a325e6679b18d08
Fixes https://github.com/Kong/kubernetes-testing-framework/issues/428
=> fix(kong addon): use postgresql.auth.username and postgresql.auth.database

CHANGELOG.md, pkg/clusters/addons/kong/addon.go
bump default kong enterprise image from 2.7.0.0 to 3.0.0.0
=> chore(kong addon) bump default kong enterprise image from 2.7.0.0 to 3.0.0.0

CHANGELOG.md, pkg/clusters/addons/kong/addon.go
Reverts Kong/kubernetes-testing-framework#432
This brakes the KTF and blocks dependant merges.
Need to investigate why dumping kong enterprise image from `2.7.0.0` to `3.0.0.0` breaks KTF.
The `TestKongEnterprisePostgres` fails on every run.  Logs shows that the version is not enterprise.
```
enterprise_test.go:90: verifying the admin api version is enterprise
enterprise_test.go:95: admin output: &{Version:3.0.0.0}
```
```go
t.Log("verifying the admin api version is enterprise")
adminOutput := struct {
Version string `json:"version"`
}{}
require.NoError(t, json.Unmarshal(body, &adminOutput))
t.Logf("admin output: %+v", &adminOutput)
require.True(t, strings.Contains(adminOutput.Version, "enterprise-edition"))
```
=> Revert "chore(kong addon) bump default kong enterprise image from 2.7.0.0 to 3.0.0.0"

.golangci.yaml, go.mod, pkg/clusters/addons/metallb/metallb.go, pkg/clusters/types/kind/utils.go, pkg/utils/kubernetes/kubectl/kustomize.go
Use `sigs.k8s.io/yaml` as the only YAML library.
See also: https://github.com/Kong/deck/pull/800 and https://github.com/Kong/go-kong/pull/239
=> chore: use consistent YAML library

.github/workflows/tests.yaml
Similar to https://github.com/Kong/kubernetes-ingress-controller/pull/3272, add `GITHUB_TOKEN` to prevent situations like these:
https://github.com/Kong/kubernetes-testing-framework/actions/runs/3766614268/jobs/6403306526#step:6:46
```
failed to deploy addon istio: couldn't fetch latest istio/istio release: GET https://api.github.com/repos/istio/istio/releases/latest: 403 API rate limit exceeded for 172.177.255.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 10m42s]
```
=> fix(tests): add GITHUB_TOKEN to tests so that they can authenticate against Github API

CHANGELOG.md, pkg/clusters/types/gke/builder.go, pkg/clusters/types/gke/builder_test.go, test/e2e/gke_cluster_test.go
Adds a possibility to create subnets for GKE clusters as a workaround for https://github.com/googleapis/google-cloud-go/issues/7219. 
**E2E tests run**:
```
=== RUN   TestGKECluster
--- PASS: TestGKECluster (0.00s)
=== RUN   TestGKECluster/create_subnet_(using_gcloud_CLI)
=== PAUSE TestGKECluster/create_subnet_(using_gcloud_CLI)
=== CONT  TestGKECluster/create_subnet_(using_gcloud_CLI)
=== CONT  TestGKECluster/create_subnet_(using_gcloud_CLI)
gke_cluster_test.go:54: configuring GKE cloud environment for tests
=== CONT  TestGKECluster/create_subnet_(using_gcloud_CLI)
gke_cluster_test.go:59: verifying integrity of the gcloud credentials
=== CONT  TestGKECluster/create_subnet_(using_gcloud_CLI)
gke_cluster_test.go:66: configuring the GKE cluster PROJECT=(k8s-team-playground) …
```
=> feat(gke): allow creating subnets

CHANGELOG.md, pkg/clusters/addons/metallb/metallb.go
The default timeout of 27s proved many times it's not enough, making our tests unstable (example run failed due to that: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3884417735/jobs/6627705020). This PR extends the timeout to 2 minutes which I believe should be enough to make the addon more stable. 
Based on https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md instructions.
=> fix(metallb): extend timeout when fetching manifests

CHANGELOG.md, pkg/clusters/types/gke/builder.go, pkg/clusters/types/gke/cluster.go, test/e2e/gke_cluster_test.go
`DeleteCluster` operation is asynchronous therefore we need to poll the operation status to tell if it's done. 
Should resolve #485.
=> feat(gke): allow synchronous cluster teardown

.github/workflows/release-testing.yaml
Affected workflow run: https://github.com/Kong/kubernetes-testing-framework/actions/runs/3891847929/jobs/6643910381
=> fix(ci): add GH token to release workflow to overcome API rate limits

pkg/clusters/types/gke/builder.go, pkg/clusters/types/gke/builder_test.go
Thankfully that was caught by the E2E test in the release pipeline: https://github.com/Kong/kubernetes-testing-framework/actions/runs/3891847929/jobs/6644691387 😓
=> fix: truncate only when allowed length exceeded

CHANGELOG.md, pkg/clusters/types/gke/builder.go
When reading the documentation again, I realized that the `--create-subnet` can be used in the gRPC API: https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#api_1.
=> refactor(gke): use grpc when createSubnet set

CHANGELOG.md, go.mod, go.sum, pkg/clusters/types/gke/builder.go
Allows passing custom labels for the GKE cluster.
=> feat(gke): allow passing labels

.github/workflows/tests.yaml, Makefile
This fixes codecov reports by specifying the `-coverpkg` in `go test` invocation.
Without this we were getting empty reports.
Link to report in codecov: https://app.codecov.io/github/Kong/kubernetes-testing-framework/commit/86098a9437aedca75a8e1b4edbb044d7f03cbdd7
=> fix: fix codecov flags

.github/workflows/tests.yaml
Similarly to https://github.com/Kong/kubernetes-ingress-controller/pull/3355, we need to checkout the repo first in order to use `go.sum` SHA as caching key.
=> fix(ci): checkout repo before go cache

CHANGELOG.md, go.mod, go.sum, pkg/clusters/addons/knative/knative.go
Sometimes accessing knative manifests fails, e.g.: https://github.com/Kong/kubernetes-testing-framework/actions/runs/4063531683/jobs/6995883947#step:6:48
```
knative_test.go:22: configuring the testing environment
knative_test.go:26: building the testing environment and Kubernetes cluster
knative_test.go:28: 
Error Trace:	/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/integration/knative_test.go:28
Error:      	Received unexpected error:
failed to deploy addon knative: knative CRD deployment failed STDOUT=() STDERR=(error: unable to read URL "https://github.com/knative/serving/releases/download/knative-v1.9.0/serving-crds.yaml", server reported 403 Forbidden, status code=403
): exit status 1
Test:       	TestEnvironmentWithKnative
--- FAIL: …
```
=> fix: add retry when applying knative manifests

CHANGELOG.md, internal/retry/command.go, pkg/clusters/addons/knative/knative.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/cleanup.go, test/integration/kongaddon_test.go
This PR adds the `retry` package that can be used to trigger commands that should be retried in case of a failure.
Closes #476 and #466
=> feat: add retry to helm installation and knative manifests apply

.github/workflows/release-testing.yaml
Fix breakage that manifested in https://github.com/Kong/kubernetes-testing-framework/actions/runs/4066204976/jobs/7002518807#step:2:6
Additionally while we're at it split integration tests into separate jobs (similarly as it was done in #416)
=> fix(ci): add missing checkout in release testing pipeline

.github/workflows/release.yaml
- No need to specify the release and tag names, otherwise they'll have `refs/tags/` prefix
- Don't mark releases as drafts or prereleases
=> fix(ci): fix release names

.github/workflows/tests.yaml, docs/install.sh
This PR aims to avoid hitting the API rate limiting by using `gh` which should already be using `GITHUB_TOKEN` on Github's CI.
=> ci: use gh in install.sh for artifacts download

test/e2e/gke_cluster_test.go
Fixes cluster not being cleaned up mentioned in #533.
=> tests(gke): ensure cluster cleanup is always called

internal/retry/command.go, internal/retry/command_test.go, pkg/clusters/addons/kong/addon.go, test/integration/kongaddon_test.go
I believe this should fix #533 root cause.
https://github.com/Kong/kubernetes-testing-framework/pull/523/files introduced `DoWithErrorHandling` which changed behavior of the helm install step of Kong addon. 
Before:
```
if err := cmd.Run(); err != nil {
if !strings.Contains(stderr.String(), "cannot re-use") { // ignore if addon is already deployed
return fmt.Errorf("%s: %w", stderr.String(), err)
}
}
```
After: 
```
return retry.
Command("helm", args...).
DoWithErrorHandling(ctx, func(err error, _, stderr *bytes.Buffer) error {
if !strings.Contains(stderr.String(), "cannot re-use") {
return fmt.Errorf("%s: %w", stderr, err)
}
return nil
})
```
In the `after` version because of `DoWithErrorHandling` implementation calling the error handling function always, despite the error value, we were …
=> fix(kong): upgrade --install and handle error properly

test/integration/kongaddon_test.go
Related https://github.com/Kong/kubernetes-testing-framework/issues/540
This PR also removes a broken test case which causes for some reason KIC to emit the following errors:
```
ingress-controller Error: either cert/key files OR cert/key values must be provided, or none
ingress-controller Error: either cert/key files OR cert/key values must be provided, or none
```
=> fix(tests): fix TestKongAddonWithCustomImage which was waiting for LoadBalancer IP without metallb installed

.github/workflows/tests.yaml
Should solve https://github.com/Kong/kubernetes-testing-framework/issues/547.
=> ci: skip e2es if no GOOGLE_APPLICATION_CREDENTIALS set

.github/workflows/tests.yaml
We should be explicit about the value we check as for some reason when the result of the first step was 'false', we still got other steps run: https://github.com/Kong/kubernetes-testing-framework/actions/runs/4117158754/jobs/7108115410.
=> ci: fix condition for running e2es

CHANGELOG.md, pkg/clusters/types/kind/utils.go
It seems that the old URL for calico manifests: https://projectcalico.docs.tigera.io/manifests/calico.yaml is not available anymore.
[Calico docs](https://docs.tigera.io/calico/3.25/getting-started/kubernetes/quickstart) explicitly mention a version in the URL so something like this has to be used: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
Since these are in the repo and not attached to release artifacts we have to pick a tag or a branch. I reckon using `master` is not the best idea so let's stick to the latest version ATM. 
Here's a CI run that has the error printed out: https://github.com/Kong/kubernetes-testing-framework/actions/runs/4144020162/jobs/7166576869
```
=== RUN   TestKindClusterWithCalicoCNI
=== PAUSE TestKindClusterWithCalicoCNI …
```
=> fix: fix calico manifests URL

pkg/clusters/types/kind/builder.go, pkg/clusters/types/kind/utils.go, pkg/clusters/utils.go
To prevent vague errors printed e.g. in tests: https://github.com/Kong/kubernetes-testing-framework/actions/runs/4143881679/jobs/7166276368#step:6:18
```
=== RUN   TestKindClusterWithCalicoCNI
=== PAUSE TestKindClusterWithCalicoCNI
=== CONT  TestKindClusterWithCalicoCNI
calico_test.go:28: configuring the test environment with Calico enabled
calico_test.go:31: building the testing environment and Kubernetes cluster
calico_test.go:33: 
Error Trace:	/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/integration/calico_test.go:33
Error:      	Received unexpected error:
exit status 1
Test:       	TestKindClusterWithCalicoCNI
--- FAIL: TestKindClusterWithCalicoCNI (36.45s)
```
this PR adds more descriptive errors in several places where we're running subcommands.
=> chore: add more descriptive errors when commands fail

CHANGELOG.md, pkg/clusters/addons/kong/addon.go, test/integration/enterprise_test.go
Apart from the version bump it fixes the test which now uses a go-kong version of parsing admin api return Kong version.
---
Fixes: #438
=> chore: bump default enterprise gateway image to 3.1.1.3

.github/workflows/lint.yaml, .github/workflows/tests.yaml, pkg/clusters/addons/certmanager/addon.go, pkg/clusters/addons/httpbin/addon.go, pkg/clusters/addons/istio/addon.go, pkg/clusters/addons/knative/knative.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kuma/addon.go, pkg/clusters/addons/loadimage/addon.go, pkg/clusters/addons/loadimage/cluster_implementations.go, pkg/clusters/addons/metallb/metallb.go, pkg/clusters/addons/registry/addon.go, pkg/clusters/cleanup_test.go, pkg/clusters/utils.go
This is a workaround to allow merging changes from external contributors. It will skip integration and e2e tests in case the required secrets are missing. 
I had to fix a couple of new linter issues that somehow started to pop up now. 
Instead of this workaround, we'll need to make the workflow runnable after some verification steps for any PR. An issue to track this effort: https://github.com/Kong/kubernetes-testing-framework/issues/596
=> ci: allow making tests workflow green for external contributors

.github/workflows/tests.yaml
To avoid spurious failures in codecov report upload like:
```
[2023-04-05T09:20:58.253Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 502 - 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```
https://github.com/Kong/kubernetes-testing-framework/actions/runs/4616788061/jobs/8162299292#step:7:103
, retry the upload 3 times instead of failing the CI.
=> chore(ci): retry codecov upload if it fails

.github/workflows/tests.yaml, test/integration/enterprise_test.go, test/integration/suite_test.go
partial of #596, enable forks to run integration tests not requiring an enterprise license.
Note: This PR is used to test the effect of running integration tests on forks.
=> test: skip cases requiring license in integration tests and update GH workflow

pkg/clusters/diagnostics.go, pkg/clusters/types/gke/cluster.go, pkg/clusters/types/kind/cluster.go, pkg/clusters/types/kind/utils.go, test/integration/kind_diagnostics_test.go, test/integration/kongaddon_test.go
Today in KTF we manually step through all the pods/objects in the cluster to get debug information. KIND now supports simply running `kind export logs` which does a better job of giving us a cluster debug overview. Switch the DumpDiagnostics function to use this command for cluster log dumping instead.
Intentionally leave the logic which allows each addon to write their own specific cleanup functionality.
=> Convert dumpDiag to use `kind export logs`

pkg/clusters/addons/knative/builder.go
Document the expected version format passed to `knative.Builder.WithVersion`.
=> chore: document knative.Builder.WithVersion

CHANGELOG.md, pkg/utils/kubernetes/networking/services.go
EndpointSlice API is available as V1 since K8s 1.21. Let's do not rely on old Endpoint API in KTF.
It's been spotted during work on https://github.com/Kong/kubernetes-ingress-controller/issues/3916.
[`TestValidationWebhook`](https://github.com/Kong/kubernetes-ingress-controller/blob/aad1dbb1513dd49a14db0f3dc8b6ad4158c2a292/test/integration/webhook_test.go#LL43C6-L43C27) from KIC [uses `WaitForConnectionOnServicePort` function](https://github.com/Kong/kubernetes-ingress-controller/blob/aad1dbb1513dd49a14db0f3dc8b6ad4158c2a292/test/integration/webhook_test.go#L682) from KTF. When KIC drops `Endpoints` in favour of `EndpointSlice` this test doesn't pass, because `Endpoints` are not created (and KTF expecting them).
Mirroring works in other way from `Endpoints` to `EndpointSlices` [under …
=> feat(k8s): Switch from CoreV1 Endpoints to DiscoveryV1 EndpointSlice

.golangci.yaml, pkg/clusters/cleanup_test.go
Configure new linters in `golangci-lint`
- [forbidgo](https://golangci-lint.run/usage/linters/#forbidigo) to prevent using old CoreV1 Endpoints API
- [importas](https://golangci-lint.run/usage/linters/#importas) ensure that `k8s.io/*` packages are imported with standardised aliases (used in other Kong projects e.g. KIC)
=> chore(ci): introduce importas and forbidigo to golangci-lint

pkg/utils/kubernetes/networking/services.go, test/integration/utils_k8s_networking_test.go
Closes #649 
PR introduces integration test for `WaitForConnectionOnServicePort` it depends on `WaitForServiceLoadBalancerAddress` which is also used in https://github.com/Kong/kubernetes-testing-framework/blob/b3347364485f45c24df0852a41ae83e68959aa08/pkg/clusters/addons/registry/addon.go#L234 (furthermore registry is covered by the test in [test/integration/registry_test.go](https://github.com/Kong/kubernetes-testing-framework/blob/26cb5599358a414da86d7af003ef3b4eed251d17/test/integration/registry_test.go)) too. So now both functions are tested.
=> chore(tests): add integration test for function WaitForConnectionOnServicePort

CHANGELOG.md, internal/retry/command.go, internal/retry/command_test.go, pkg/clusters/addons/metallb/metallb.go
This also adds a retry to metallb addon's deploy and delete functions.
=> feat: allow setting stdin, stdout and stderr in retry command

CHANGELOG.md, pkg/clusters/types/kind/builder.go, pkg/clusters/types/kind/utils.go, test/integration/kind_cluster_test.go
Passing config to Kind cluster with file path is tedious and inconvenient. Add method  `WithConfigReader(cfg io.Reader)` to Kind builder to allow passing arbitrary YAML without requiring having a concrete file for it.
=> feat(kind): allow passing config for Kind clusters with io.Reader

.github/workflows/tests.yaml
The existing `integration-tests-passed` condition passes even when some of the integration tests failed, e.g. https://github.com/Kong/kubernetes-testing-framework/actions/runs/5241672836/jobs/9464102490?pr=703.
This PR tries to address this.
=> ci: fix integration tests aggregate check

.github/workflows/tests.yaml, Makefile, test/e2e/gke_cluster_test.go
This PR makes the e2e tests to run in separate jobs, this making the CI faster by parallelizing the tests.
Similar approach has already been done for integration tests: https://github.com/Kong/kubernetes-testing-framework/blob/cb3a483e674ad2305b21de77d731d7a9a8b92b8b/.github/workflows/tests.yaml#L69-L86
=> ci: use separate CI jobs for e2e tests

test/e2e/gke_cluster_test.go, test/integration/calico_test.go, test/integration/certmanager_test.go, test/integration/cleaner_test.go, test/integration/clusterutils_test.go, test/integration/enterprise_test.go, test/integration/istio_test.go, test/integration/kind_cluster_test.go, test/integration/kind_diagnostics_test.go, test/integration/kind_version_test.go, test/integration/knative_test.go, test/integration/kongaddon_test.go, test/integration/kuma_test.go, test/integration/metallb_test.go, test/integration/postgres_test.go, test/integration/registry_test.go, test/integration/suite_test.go, test/integration/utils_k8s_networking_test.go
**What this PR does / why we need it**:
Since Go 1.18 the new directive `//go:build` is now preferred and the toolchain will actively remove old directives; as mentioned in Go 1.18 release notes:
> In Go 1.18, go fix now removes the now-obsolete // +build lines in modules declaring go 1.18 or later in their go.mod files.
KIC  specifies in `go.mod` Go version `1.20`.
**Which issue this PR fixes**:
It's part of the https://github.com/Kong/team-k8s/issues/286
=> chore(build): get rid of obsolete Go build tags

pkg/environments/builder.go, test/e2e/kind_cluster_test.go
**What this PR does / why we need it:**
When method `Build()` for cluster builder returns an error no leftovers should be left, especially full cluster when for instance deployment of one of the add-ons failed.
=> fix: deletion of cluster when Build method returns error

pkg/clusters/diagnostics.go, pkg/clusters/types/gke/cluster.go, pkg/clusters/types/kind/cluster.go, pkg/environments/implementation.go
If the cluster fails to become ready after 20 minutes, assume it's stuck and dump a diagnostic.
At present unready clusters will just hit the test timeout and exit without providing any useful information.
=> feat: dump diagnostics if cluster not ready

CHANGELOG.md, pkg/clusters/utils.go
Allow passing additional flags to `KustomizeDeployForCluster` and `KustomizeDeleteForCluster`.
=> feat: allow passing additional flags to kubectl kustomize

CHANGELOG.md, pkg/clusters/utils.go
Makes `KustomizeDeployForCluster` and `KustomizeDeleteForCluster` always use a cluster's temporary kubeconfig file instead of the default one.
=> feat: use kubeconfig in kustomize cluster helpers

pkg/clusters/addons/kong/addon.go
One or more strings can be passed directly as second arguments to `append` function, it doesn't need to be a string slice, that is later unpacked with `...` operator.
=> refactor(go): get rid of redundant slices in append function

internal/test/assert.go, test/integration/enterprise_test.go
Currently, only Kong Enterprise deployed with Postgres is covered with tests. Refactor by extracting common pieces to make it easy to add a new test for DBLess mode.
Moreover, add a check that the workspace (enterprise feature) has been indeed created in a Kong Gateway (checking directly in API since this test checks to create Kong Gateway that runs in enterprise mode.
In the next separate PR support for DBLess will be tested.
=> refactor: introduce reusable test helpers

CHANGELOG.md, pkg/clusters/addons/kong/addon.go, test/integration/enterprise_test.go
This PR fixes KTF to allow deployment of Kong Gateway EE in DBLess mode. New introduced test `TestKongEnterpriseDBLess` checks it. The adjustment has to be made for tests for the enterprise version. Instead of using `/workspaces` that silently doesn't work in DBLess mode when trying to configure them - nothing is created (will be reported to the upstream, but it's rather considered as normal, old, expected behavior) `/consumer_groups` are used. Consumer Groups work in the same way in both versions.
=> fix: allow to deploy Kong Gateway EE in DBLess mode

CHANGELOG.md, pkg/clusters/addons/kong/builder.go, test/integration/kongaddon_test.go
support to specify namespace of Kong addon to deploy Kong in certain namespace. Fixes #765
=> support setting namespace in kong addon

CHANGELOG.md, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go, test/integration/kongaddon_test.go
Fix: set `udpProxy.type` to specified proxy service type, because `udpProxy` service is enabled by default and has type `LoadBalancer` by default. By setting this we can set `proxyServiceType` to `ClusterIP` to get rid of dependency on `metallb` in unnecessary test cases. Fixes #540.
=> fix: set udpProxy.type to proxyServiceType specified

CHANGELOG.md, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go
Adds `WithHelmChartVersion` and `WithProxyReadinessProbePath` Kong addon builder methods. Modifies the `WithControllerDisabled` method to also alter the `proxyReadinessProbePath` to `/status` so that the installation succeeds if the controller is disabled (otherwise `/status/ready` default would be used which expects Gateway to have a non-empty config loaded/configured).
=> feat(kong): allow customizing chart version and proxy readiness probe

pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go
support setting arbitrary values in installing kong by helm to support setting `images.effectiveSemver` to fix parsing semver in s integration tests against kong nightly image.
REVIEW: move the setting of other values to `addon.addtionalValues`?
=> feat: support arbitrary values in helm install

CHANGELOG.md
add CHANGELOG items for new version and entry for setting arbitrary values of kong addon.
REVIEW: name next release as `v0.37.0`?
=> chore: add CHANGELOG entry for setting additional value of helm

CHANGELOG.md, pkg/clusters/addons/kong/builder.go
Function name had a hard to spot misspelling.
It's a breaking API change, but recent enough that I don't think we should bother deprecating it. AFAIK we only use it in `KIC:test/internal/helpers/ktf.go`.
=> fix: correct misspelled function name

test/e2e/gke_cluster_test.go
It bumps GKE K8s to `1.24`, because `1.23` [reached EOL 2023-07-31](https://cloud.google.com/kubernetes-engine/docs/release-schedule) and it [failed CI](https://github.com/Kong/kubernetes-testing-framework/actions/runs/6086727177).
=> chore(ci): Bump GKE K8s version from 1.23 to 1.24

go.mod
Since the version of Docker in GH runners has been updated, the explicit exclusion of 
```
github.com/docker/docker v24.0.0+incompatible
```
is no longer needed. Closes
- #670
=> chore(deps): remove exclude github.com/docker/docker v24.0.0+incompatible

CHANGELOG.md
The exclude was quite annoying when I was trying to update, and doubly annoying when I was looking at main and not seeing it. We should release to fix the install docs.
=> chore: release 0.39.1

pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go, pkg/clusters/addons/kong/vars.go, pkg/clusters/addons/metallb/metallb.go
Add possibility to specify NodePorts for kong's admin API and HTTP port.
This is required for https://github.com/Kong/kubernetes-ingress-controller/pull/4823 to prevent tests colliding when deploying multiple kong addons to the same cluster.
=> feat(kong): allow setting Node ports

CHANGELOG.md, pkg/clusters/addons/metallb/metallb.go
Update metallb. This is mostly to pull in https://github.com/metallb/metallb/pull/2097
We previously set the addon to delete any existing pool if one with the desired name already exists in https://github.com/Kong/kubernetes-testing-framework/issues/381
Earlier metallb versions handled pool changes by keeping Service IPs assigned by the previous pool. These IPs would become unrouteable and rather useless. We could probably adjust the reuse conflict by just letting the old pool remain instead of deleting it and creating a new one instead, but I'm opting to leave this behavior as-is since the latest metallb does handle it.
~Draft to see if I can't actually do this because our test suites aren't smart enough to update their IPs.~ From some basic testing with the KIC integration tests, it …
=> chore: update metallb to 0.13.12 and release

.golangci.yaml, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/builder.go
**What this PR does / why we need it**:
This PR adjusts the configuration of golangci-lint, to get rid of `//nolint:exhaustive`. It is sensible always to treat `switch` statements that include case `default` as exhaustive.
Also, it fixes a typo in forbidigo configuration.
=> chore(linter): in switch case default signifies exhaustive match and fix forbidigo

CHANGELOG.md, pkg/clusters/addons/kong/addon.go
PR https://github.com/Kong/kubernetes-testing-framework/pull/867 bumped image from `3.3.-alpine` to `3.4-alpine` despite failures in tests ([this](https://github.com/Kong/kubernetes-testing-framework/actions/runs/6773122543/job/18407259479) and [that](https://github.com/Kong/kubernetes-testing-framework/actions/runs/6773122543/job/18407259793)) it was successfully merged. A fix for this to not allow merging is presented in 
- https://github.com/Kong/kubernetes-testing-framework/pull/869
Since `3.4` the Alpine image is no longer built, the recommended one is Ubuntu so this PR is setting it.
=> fix: change Kong Gateway Enterprise default image to Ubuntu

.github/workflows/tests.yaml
PR https://github.com/Kong/kubernetes-testing-framework/pull/867 bumped image from `3.3.-alpine` to `3.4-alpine` despite failures in tests ([this](https://github.com/Kong/kubernetes-testing-framework/actions/runs/6773122543/job/18407259479) and [that](https://github.com/Kong/kubernetes-testing-framework/actions/runs/6773122543/job/18407259793)) it was successfully merged. 
This PR fixes it, it should not allow merge when any test fails, a fix for a bump of the image is in 
- https://github.com/Kong/kubernetes-testing-framework/pull/868
=> fix(ci): fail integration-tests-passed when tests don't pass

.github/workflows/release-testing.yaml, .github/workflows/tests.yaml
This change is required to accommodate the forthcoming work in https://github.com/Kong/kong-license/pull/25
That work will change kong-license such that the license is sourced directly from 1Password, rather than it being sourced from Pulp using credentials from 1Password (as is the case today). Meaning that workflows needing to run Kong/kong-license's will require 1P credentials instead of the Pulp password.
This work is a necessary step in the deprecation of Pulp aka [KAG-2247](https://konghq.atlassian.net/browse/KAG-2247) / [KAG-3254](https://konghq.atlassian.net/browse/KAG-3254).
Leaving the Pulp password for now so that https://github.com/Kong/kong-license/pull/25 can be merged *after* this PR.
[KAG-2247]: https://konghq.atlassian.net/browse/KAG-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> chore(gha): preemptively add 1p creds

.github/workflows/release-testing.yaml, .github/workflows/tests.yaml
After https://github.com/Kong/kong-license/pull/25 has been merged, we only care about 1Password token so remove the reference to Pulp password.
=> chore(ci): remove pulp password usage

CHANGELOG.md, pkg/clusters/types/gke/builder.go, test/e2e/gke_cluster_test.go
Allow specifying a release channel to use images from when creating a GKE cluster. It allows setting all of the existing release channels Google maintains ([release notes](https://cloud.google.com/kubernetes-engine/docs/release-notes)).
=> feat: add WithReleaseChannel to GKE cluster builder

.github/workflows/release.yaml
Reverts major version bumps of actions/upload-artifact and actions/download-artifact to v4 that introduced breaking changes that we do not have yet direct remedy for. Created an issue to track this: https://github.com/Kong/kubernetes-testing-framework/issues/912
=> Revert actions/upload-artifact and actions/download-artifact bumps to v4

CHANGELOG.md, pkg/utils/docker/client.go, pkg/utils/docker/command.go, pkg/utils/docker/copy.go, pkg/utils/docker/docker.go
When a Docker daemon doesn't support an API version that's used by the Go client, it will reject communication as in the [issue we've faced in KIC](https://github.com/Kong/kubernetes-ingress-controller/pull/5464#issuecomment-1902932869). This change is to avoid such errors by making sure that the client downgrades the API automatically in case the daemon doesn't support the newest one.
Should unblock https://github.com/Kong/kubernetes-testing-framework/pull/931.
=> fix: negotiate Docker API version

CHANGELOG.md, pkg/clusters/addons/kuma/addon.go, pkg/clusters/addons/kuma/builder.go, test/e2e/gke_cluster_test.go
In Kuma addon builder we allow setting a version, but we don't use it when calling `helm install`.
=> feat: use kuma version when installing it

CHANGELOG.md, pkg/clusters/addons/kuma/addon.go
In 2.6.0 Kuma stopped creating default traffic permissions. This PR aims to preserve the previous behavior so that all traffic is allowed as before. 
Kuma upgrade notes: https://github.com/kumahq/kuma/blob/2.6.0/UPGRADE.md#default-trafficroute-and-trafficpermission-resources-are-not-created-when-creating-a-new-mesh
=> feat: install default allow-all traffic permission when kuma >= 2.6.0

CHANGELOG.md, pkg/clusters/addons/kuma/addon.go, pkg/clusters/addons/kuma/builder.go
Add support for arbitrary chart settings to the Kuma plugin, inspired by the existing Kong plugin functionality.
I added this to test some additional Kuma settings in CI to try and find some fix for the KIC session stickiness issues we've seen with Kong 3.6. Didn't find any fix, but this is generic enough that we may as well add it anyway.
=> feat: support arbitrary Kuma Helm values

.github/workflows/lint.yaml, .github/workflows/tests.yaml, CHANGELOG.md, internal/cmd/ktf/environments.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kuma/addon.go, pkg/clusters/addons/kuma/builder.go, pkg/environments/builder.go, pkg/utils/kong/fake_admin_api.go, test/e2e/gke_cluster_test.go
Backport https://github.com/Kong/kubernetes-testing-framework/commit/fe761fa03cc425dbc3c76bcd35246b5fc41b9ca7 and https://github.com/Kong/kubernetes-testing-framework/commit/78164723d50b1012015d938c9cf4dc7720219c3e to 0.39 and release 0.39.2.
Update CI to test on PRs to release branches. Update license handling for this release branch.
---
KIC 2.12 is able to pass E2E with this in place: https://github.com/Kong/kubernetes-ingress-controller/pull/5760#issuecomment-2026047921
---
This technically breaks semver, but we don't really have anywhere else to stuff it. Maybe you can call the addon not supporting version args and not supporting 2.6 "bugs" for the sake of discussion :shrug: 
Updating KIC 2.x to use the latest KTF causes [all sorts of …
=> Backport Kuma updates to 0.39

.github/workflows/release-testing.yaml
Fix for https://github.com/Kong/kubernetes-testing-framework/actions/runs/8479160134/job/23232712143.
=> chore(ci): fix release workflow's license step

CHANGELOG.md, pkg/utils/kubernetes/kubectl/kustomize.go
Publish a previously private helper. If you have an existing complete kustomization dir whose result isn't already built, this function lets you build it and get the result, as `[]byte`.
Release 0.47
=> feat: publish kubectl.RunKustomize

.golangci.yaml, internal/cmd/ktf/environments.go, internal/cmd/ktf/init.go, pkg/clusters/addons/kong/addon.go, pkg/clusters/addons/kong/enterprise_test.go, pkg/clusters/addons/kuma/addon.go, pkg/clusters/addons/metallb/metallb.go, pkg/clusters/addons/registry/addon.go, pkg/clusters/cleanup.go, pkg/clusters/diagnostics.go, pkg/clusters/types/gke/cluster.go, pkg/clusters/types/kind/utils.go, pkg/environments/builder.go, pkg/utils/kubernetes/kubectl/kustomize.go, pkg/utils/networking/http.go
Since `gocritic` has been introduced in
- https://github.com/Kong/gateway-operator/pull/101
- https://github.com/Kong/kubernetes-ingress-controller/pull/5899
let's keep our coding standards consistent across managed projects and use `gocritic` in KTF too.
Moreover, it does housekeeping like fixing all warnings of deprecated linters, adjusting config, etc.
=> chore(lint): enable gocritic and fix reported issues

.github/workflows/codeql-analysis.yml, .github/workflows/release-testing.yaml, .github/workflows/release.yaml, internal/cmd/ktf/environments.go, internal/cmd/ktf/init.go
Supersedes #950, #952, #953, #954
Naming fix [inits -> gochecknoinits](https://golangci-lint.run/product/changelog/#v1581)
=> chore(ci): set timeouts in remaining CI files and adjust linter name in //nolint

CHANGELOG.md, pkg/clusters/addons/kong/addon.go
`kong/kong` chart from v2.39 no longer sets the default value of `enterprise.rbac.session_conf_secret` (https://github.com/Kong/charts/pull/1033). This PR fixes an issue discovered in KIC's integration tests (https://github.com/Kong/kubernetes-ingress-controller/pull/6198) that makes Kong complain about missing `admin_gui_session_conf` caused by KTF relying on the default in charts.
Tested in https://github.com/Kong/kubernetes-ingress-controller/pull/6198 by manual KTF bump to this branch.
=> fix: adapt to kong chart v2.39

.github/workflows/release-testing.yaml
Drop the e2e tests job's timeout set from organization's vars as it's not enough: https://github.com/Kong/kubernetes-testing-framework/actions/runs/9550375317/job/26324041269
=> chore: extend e2e tests' timeout

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yaml, .github/workflows/release-testing.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml
Using variables is not supported in PRs from forks, ref: https://github.com/orgs/community/discussions/44322
This PR hardcodes the timeouts (as these are the only variables that are used) to enable PRs from forks to be accepted.
=> chore(ci): hardcode timeouts

.github/workflows/tests.yaml
v5 action doesn't seem to be compatible with `Wandalen/wretry.action`:
https://github.com/Kong/kubernetes-testing-framework/actions/runs/12883517600/job/35917923256
```
Error: Runner "composite" does not implemented.
Please, search/open a related issue.
```
=> ci: do not run codecov for PRs from forks, update codecov to v4

.github/workflows/release.yaml
Fix: https://github.com/Kong/kubernetes-testing-framework/actions/runs/16810322113/job/47613821381
```
⚠️ GitHub release failed with status: 403
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release","status":"403"}
Skip retry — your GitHub token/PAT does not have the required permission to create a release
Error: Resource not accessible by integration - https://docs.github.com/rest/releases/releases#create-a-release
```
=> chore(ci): fix release permissions
