Kong/kubernetes-testing-framework

pkg/helm/kong.go, pkg/kind/kong_cluster.go, test/integration/kind_cluster_test.go
Helps to resolve https://github.com/Kong/kubernetes-ingress-controller/issues/1253
=> feat: enable postgres backed proxy deployments in test framework

CONTRIBUTING.md, README.md, pkg/kong/doc.go, test/integration/doc.go
This includes several misc. updates to documentation.
=> Docs Cleanup

pkg/clusters/addons/kong/kong.go, pkg/environments/builder.go
Fixes two bugs I found while updating KIC to the latest KTF version.
=> various bug fixes

pkg/clusters/types/gke/builder.go
Resolves https://github.com/Kong/kubernetes-testing-framework/issues/68
=> fix: disable gke addons

Makefile, pkg/clusters/addons/istio/addon.go, test/integration/enterprise_test.go, test/integration/generators_test.go, test/integration/istio_test.go, test/integration/kind_cluster_test.go, test/integration/kind_version_test.go, test/integration/knative_test.go, test/integration/metallb_test.go, test/integration/postgres_test.go
This is a follow up from #122 and adds a couple of convenience methods that are helpful for logging and reporting in tests.
=> feat: namespace and version methods for istio addon

pkg/clusters/addons/kong/addon.go
In which I realize that I copied something I shouldn't have and rectify that to make UDP work again.
=> fix: don't overwrite UDP listen

CHANGELOG.md
=> doc: add 0.13.0 changelog

CHANGELOG.md, pkg/clusters/addons/metallb/metallb.go
=> chore: upgrade metallb to v0.12.1

pkg/utils/kubernetes/networking/services.go
Implement An approach to test TCP connectivity of a service by creating a temp LB service. fixes #331.
=> feat: wait for service connective by TCP

pkg/clusters/cleanup.go
Change the `kubectl get` and `kubectl describe` invocations in the cleaner diagnostics to get more than it used to. The `all` in `kubectl get all` (the original invocation) only retrieves resources that meet certain criteria, excluding custom resources and cluster-level resources. We do want these also.
=> fix: include all resources in diag get

pkg/clusters/addons/loadimage/addon.go, pkg/clusters/addons/loadimage/builder.go, pkg/clusters/addons/loadimage/cluster_implementations.go
support loading multiple images in loadimage addon. fixes #366.
=> feat: load multiple images in loadimage addon

CHANGELOG.md
update `CHANGELOG.md` for releasing v0.22.0.
=> chore:  release 0.22

.github/workflows/tests.yaml, docs/install.sh
Address leftover items from #516 review.
=> chore: address review from PR 516

pkg/clusters/addons/kuma/addon.go
This aims to avoid rate limiting issues like: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4190728388/jobs/7264432883#step:6:68
```
kuma_test.go:94: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/e2e/kuma_test.go:94
Error:      	Received unexpected error:
failed to deploy addon kuma: Error: INSTALLATION FAILED: failed to fetch https://github.com/kumahq/charts/releases/download/kuma-2.1.1/kuma-2.1.1.tgz : 429 Too Many Requests
: exit status 1
Test:       	TestDeployAllInOnePostgresKuma
```
This in all fairness could be handled by github tokens and through some sort of helm flags but `helm install --username USER --password $GITHUB_TOKEN` doesn't seem to increased the used github API quota for me. What's even more …
=> feat: add retry to kuma helm installation

CHANGELOG.md, pkg/clusters/types/gke/builder.go
Related: https://github.com/Kong/kubernetes-ingress-controller/issues/3555
=> feat: add machine type param to gke cluster builder

go.mod, go.sum
=> chore: fix tests on CI by downgrading docker dependency

.golangci.yaml
Similar to https://github.com/Kong/go-kong/pull/337
=> chore: update gomodguard config

CHANGELOG.md, pkg/clusters/addons/metallb/metallb.go
https://github.com/metallb/metallb/releases/tag/v0.13.10
=> chore: bump metallb to v0.13.10

test/integration/kongaddon_test.go
For some reason (perhaps with Kong Gateway 3.3) the 404 response from proxy URL changed to contain more whitespaces:
```
{
"message":"no Route matched with those values"
}
```
This PR accounts for that and simply parses the response body instead of asserting verbatim its contents.
=> tests: fix TestKongWithNodePort integration test

CHANGELOG.md
release KTF 0.35 with the 3 changes in the CHANGELOG.
=> release 0.35 and add ArgoCD to CHANGELOG

pkg/clusters/addons/metallb/metallb.go
related: https://metallb.universe.tf/release-notes/#version-0-13-11
=> chore(deps): bump metallb to v0.13.11

pkg/clusters/addons/certmanager/addon.go
cert-manager install currently fails if there's already a job present. This copies code to delete it out of `Delete()` into `Deploy()` to more or less match the behavior of other resources (we run a `kubectl apply`, which will overwrite all the other non-immutable resources.
This does leave abandoned completed Job Pods around, but I don't really mind those.
Example failure with current code:
```
...
INFO: using existing kind cluster kind
> [unrecovered-panic] runtime.fatalpanic() /usr/lib/go/src/runtime/panic.go:1217 (hits goroutine(1):1 total:1) (PC: 0x1303104)
Warning: debugging optimized function
runtime.curg._panic.arg: interface {}(string) "ERROR: failed to deploy addon cert-manager: could not create job...+89 more"
...
(dlv) frame 2
...
(dlv) p err
error(*fmt.wrapError) *{
msg: …
```
=> feat: delete cert-manager jobs on install

.github/workflows/lint.yaml, .github/workflows/release-testing.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml
Pin all imported 3rd party actions by their hashes.
=> Chore: pin 3rd party actions by hashes
